services:
  telegramnotifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:50"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
